# ref: https://docs.travis-ci.com/user/languages/python
language: python
dist: xenial

matrix:
    include:
     - python: 3.6
       env: TOXENV=py36
     - python: 3.7
       env: TOXENV=py37
     - python: 3.7
       env: TOXENV=cover,docs,flake8
     - python: 3.8
       env: TOXENV=py38

install:
  - pip install tox

script:
  - tox
