[project]
name = "pyds8k"
description = "DS8000 Python Client"
dynamic = ["version"]
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.9"
authors = [
    { name = "Zhang Wu", email = "shwzhang@cn.ibm.com" },
]
maintainers = [
    { name = "Randy Blea", email = "blead@us.ibm.com" },
    { name = "NjM3MjY5NzAgNzA3MzA3", email = "102704081+NjM3MjY5NzAgNzA3MzA3@users.noreply.github.com" },
]
keywords = [
    "IBM",
    "DS8000 Storage"
]
classifiers=[
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Intended Audience :: System Administrators',
    'Environment :: Console',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Topic :: Software Development :: Libraries :: Python Modules',
]
dependencies = [
    "requests>=2.31.0",
]
[dependency-groups]
dev = [
    "sphinx>=2.2.1",
    "ruff>=0.11.6",
]
test = [
    "pytest>=7.0.0",
    "pytest-cov>=3.0.0",
    "mock>=3.0.5",
    "httpretty>=0.9.6",
    "tox>=4.22.0"
]

[build-system]
requires = ["setuptools >= 77.0.0"]
build-backend = "setuptools.build_meta"

[project.urls]
Documentation = "https://pyds8k.readthedocs.io/en/latest"
Homepage = "https://github.com/IBM/pyds8k"
Issues = "https://github.com/IBM/pyds8k/issues"
Repository = "https://github.com/IBM/pyds8k.git"

[tool.setuptools.dynamic]
version = {attr = "pyds8k.version"} # Set in pyds8k/__init__.py

[tool.setuptools.packages.find]
exclude = ["cover", "images"]

[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.9
target-version = "py39"

[tool.ruff.lint]
extend-select = [
    "EM",
    "I",
    "PIE",
    "PYI",
    "RET",
    "RSE",
    "SIM"
]

ignore = [
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"pyds8k/example.py" = ["T201"] # allow print

[tool.ruff.format]
# Project has mixed strings
quote-style = "preserve"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
