[tox]
minversion = 4.22.0
skipdist = True
envlist = py3{9,10,11,12,13},flake8,cover,docs

[testenv]
setenv = VIRTUAL_ENV={envdir}
usedevelop = True
install_command = pip install {opts} {packages}

dependency_groups = test
commands =
  pytest --disable-warnings -v {posargs}

[testenv:cover]
dependency_groups = test
commands =
  pytest --cov-config=.coveragerc --cov pyds8k --disable-warnings -v {posargs}

[testenv:docs]
dependency_groups = dev
commands =
  sphinx-build -b html docs docs/html

[testenv:flake8]
dependency_groups = dev
commands =
  flake8 {posargs} --exclude=./pyds8k/tests/ ./pyds8k
